[project]
name = "csc713m-mco"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "counter>=1.0.0",
    "image>=1.5.33",
    "ipykernel>=7.2.0",
    "kaggle>=2.0.0",
    "kagglehub>=1.0.0",
    "opencv-python>=4.13.0.92",
    "path>=17.1.1",
    "plt>=0.2.0",
    "scikit-learn>=1.8.0",
    "tensorflow>=2.21.0",
]
